config/routes.rb
CreateExam::Application.routes.draw do

  root :to => 'exams#index'

  resources :exams do
    resources :questions do
      resources :answers
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :desc, :image
  belongs_to :question
  validates :desc, :presence => true,
                   :length => { :minimum => 1 }
  mount_uploader :image, ImageUploader
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  attr_accessible :name, :owner
  has_many :questions, :dependent => :destroy
  validates :name, :presence => true,
                   :length => { :minimum => 1 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description, :ques_type, :image
  belongs_to :exam
  has_many :answers
  validates :description, :presence => true,
                    :length => { :minimum => 1 }
  mount_uploader :image, ImageUploader
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :find_question
  
  def find_question
    @exam = Exam.find(params[:exam_id])
    @question = @exam.questions.find(params[:question_id])
  end

  # GET /answers
  # GET /answers.json
  def index
    @answers = @question.answers.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  # def show
  #   @answer = @question.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @answer }
  #   end
  # end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = @question.answers.new

    respond_to do |format|
      format.html { render :template => "answers/form"}
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      format.html { render :template => "answers/form"}
      format.json { render json: @answer }
    end
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @question.answers.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to exam_questions_path(@exam), notice: 'Answer was successfully created.' }
        format.json { render json: exam_questions_path(@exam), status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: exam_questions_path(@exam).errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to exam_questions_path(@exam), notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: exam_questions_path(@exam).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = @question.answers.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all

    respond_to do |format|
      if params[:create_exam].present? 
        format.html { 
          flash[:notice] = 'Exam created successfully.'
          render :template => "exams/index"
        }
      else
        format.html # index.html.erb
      end
      format.json { render json: @exams }
    end
  end

  # GET /exams/1
  # GET /exams/1.json
  # def show
  #   @exam = Exam.find(params[:id])
  #   @question = @exam.questions.build

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @exam }
  #   end
  # end

  # GET /exams/new
  # GET /exams/new.json
  def new
    @exam = Exam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/1/edit
  def edit
    @exam = Exam.find(params[:id])
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(params[:exam])

    respond_to do |format|
      if @exam.save
        format.html { redirect_to exams_path, notice: 'Exam was successfully created.' }
        format.json { render json: exams_path, status: :created, location: @exam }
      else
        format.html {  
          flash[:error] = 'Exam name can not be left blank.'
          render action: "new"
        }
        format.json { render json: exams_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exams/1
  # PUT /exams/1.json
  def update
    @exam = Exam.find(params[:id])

    respond_to do |format|
      if @exam.update_attributes(params[:exam])
        format.html { redirect_to exams_path, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :find_exam
  
  def find_exam
    @exam = Exam.find(params[:exam_id])
  end

  # GET /questions
  # GET /questions.json
  def index
    @questions = @exam.questions.all
    @question = @exam.questions.build

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = @exam.questions.find(params[:id])
    ques_ids = @exam.questions.map(&:id)
    @current_ques_index = ques_ids.index(@question.id.to_i)
    @prev_ques_id = ques_ids[@current_ques_index - 1] if @question.id!=ques_ids.first
    @next_ques_id = ques_ids[@current_ques_index + 1] if @question.id!=ques_ids.last

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = @exam.questions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = @exam.questions.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = @exam.questions.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to exam_questions_path(@exam), notice: 'Question was successfully created.' }
        format.json { render json: exam_questions_path(@exam), status: :created, location: @question }
      else
        format.html {  
          flash[:error] = 'Question description can not be left blank.'
          redirect_to exam_questions_path(@exam)
        }
        format.json { render json: exam_questions_path(@exam).errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = @exam.questions.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to exam_questions_path(@exam), notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = @exam.questions.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<table>
  <% if answer.id.present? %>
    <tr id="<%= answer.id%>">
      <td><%= link_to image_tag( 'edit.png', :border=>0, :title=>'Edit', :size => "16x16"), edit_exam_question_answer_path(answer.question.exam, answer.question, answer) %></td>
      <td><%= link_to image_tag( 'iconDelete.gif', :border=>0, :title=>'Delete', :size => "16x16"), [answer.question.exam, answer.question, answer], :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
      <% ques_type = answer.question.ques_type %>
      <% if ques_type == "Radio Button" %>
      	<td width='20'><%= image_tag( 'radio_button.png', :border=>0, :size => "16x16") %></td>
      <% elsif ques_type == "CheckBox" %>
      	<td width='20'><%= image_tag( 'checkbox.gif', :border=>0, :size => "16x16") %></td>
      <% else %>
      	<td width='20'>None</td>
      <% end %>
      <td width='950'><%= answer.desc %></td>
    </tr>
    <% if answer.image_url.present? %>
      <tr><td colspan='3' align='center'><%= image_tag answer.image_url(:thumb).to_s %></td></tr>
    <% end %>
  <% end %>
</table>

app/views/answers/_answer_form.html.erb
<table id="take_exam_question">
  <%#= form_tag(set_project_phase_projects_path, :method => "put", :remote => true) do %>
    <% @question.answers.each do |answer| %>
      <% if answer.id.present? %>
        <tr id="<%= answer.id%>">
          <% ques_type = answer.question.ques_type %>
          <% if ques_type == "Radio Button" %>
          	<td width='20'><%= radio_button_tag "answer[]", answer.id %></td>
          <% elsif ques_type == "CheckBox" %>
          	<td width='20'><%= check_box_tag "answer[]", answer.id %></td>
          <% end %>
          <td width='950'><%= answer.desc %></td>
        </tr>
        <% if answer.image_url.present? %>
          <tr>
            <td colspan='2' align='center'><%= image_tag answer.image_url(:thumb).to_s %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
    <tr>
      <td colspan='2' align='center'><%= submit_tag("Submit Answer")%></td>
    </tr>
  <%# end %>
</table><br/>

<table width="100%">
  <tr width="100%">
    <td width="50%"><%= link_to '<< Previous Question', exam_question_path(@exam, @prev_ques_id), :id => "each_number" if @prev_ques_id.present? %></td>
    <td align='right' width="50%"><%= link_to 'Next Question >>', exam_question_path(@exam, @next_ques_id), :id => "each_number" if @next_ques_id.present? %></td>
  </tr>
</table>

app/views/answers/destroy.js.erb
$("#" + <%= @answer.id%>).hide();

app/views/answers/form.html.erb
<% if @question.id.present? %>
	<%= form_for([@exam, @question, @answer]) do |f| %>
	  <div class="field">
	    <%= f.label :desc %><br />
	    <%= f.text_area :desc %>
	  </div>
	  <%= f.file_field :image %>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
<% end %>

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/destroy.js.erb
$("#" + <%= @exam.id%>).hide();

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<h1>Listing exams</h1>

<table class="exam_list">
  <tr style="background:#71ACDD;">
    <th>Name</th>
    <th>Owner</th>
    <th>Add/View Questions</th>
    <th>Take Exam</th>
    <th>Edit Exam</th>
    <th>Delete Exam</th>
  </tr>

<% @exams.each do |exam| %>
  <tr id="<%= exam.id%>">
    <td width='300'><%= exam.name %></td>
    <td width='150'><%= exam.owner %></td>
    <td><%= link_to 'Questions', exam_questions_path(exam) %></td>
    <td><%= link_to 'Take Exam', exam_question_path(exam, exam.questions.first) %></td>     
    <td><%= link_to image_tag( 'edit.png', :border=>0, :title=>'Edit', :size => "16x16"), edit_exam_path(exam) %></td>
    <td><%= link_to image_tag( 'iconDelete.gif', :border=>0, :title=>'Delete', :size => "16x16"), exam, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
  </tr>
<% end %>
</table>

app/views/exams/new.html.erb
<h1>New exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam Builder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">

  <div id="header">
    <div id="home_icon">
      <%= link_to image_tag( 'home.png', :border=>0, :title=>'Home', :size=>'60x60', :align=>'left'), exams_path %>
    </div>
    <div id="home_title">
      <b>Exam Builder</b>
    </div>
  </div>

  <div id="login_user">
    <%= link_to 'Sample Exams', exams_path %>
    || <%= link_to "Create Exam", new_exam_path %>
    || <%#= link_to 'Take Exam', new_agenda_path %>
  </div> 

  <div id="body">
    <% if flash[:error] %>
      <p id='error'><%=h flash[:error] %></p>
    <% end -%>
    <% if flash[:notice] -%>
      <p id='notice'><%=h flash[:notice] %></p>
    <% end %>
    <%= yield %></br></br>
  </div>

  <div id="footer">
    <h5>Developed by Himanshu Gupta</h5>  
  </div>
</div>
</body>
</html>

app/views/questions/_add_question_dialog.html.erb
<!-- modal window to add new question -->
<div id="dialog-form" title="Add Another Question" style="display:none">  
  <div id="modal_question_form">
    <p class="validateQuestion" style="display:none">Question Description field can not be blank.</p> 
    <%= render "questions/form" %>
  </div>
</div>

app/views/questions/_dialog.html.erb
<!-- modal window to add new question -->
<div id="dialog-form" title="Add Another Question" style="display:none">  
  <div id="modal_question_form">
    <p class="validateQuestion" style="display:none">Question Description field can not be blank.</p> 
    <%= render "questions/form" %>
  </div>
</div>

app/views/questions/_edit_question_dialog.html.erb
<!-- modal window to edit a question -->
<div id="dialog-form" title="Edit Question" style="display:none">  
  <div id="modal_question_form">
    <p class="validateQuestion" style="display:none">Question Description field can not be blank.</p> 
    <%= render "questions/form" %>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_for([@exam, @question], :html => {:multipart => true}) do |f| %>
  <div class="field">
    <%= f.text_area :description, :rows => 5, :placeholder => "Question..." %>
  </div><br/>
  <div class="field">
    Type of Question : 
    <%= f.select :ques_type, options_for_select([["Radio Button", "Radio Button"], ["CheckBox","CheckBox"]]) %>
  </div>
  <%= f.file_field :image %><br/><br/>
  <div class="actions" id="submit_question">
    <%= f.submit "Submit" %>
  </div>
<% end %>

<script>
$("#submit_question").click(function() {
  if($("#question_description").val().length < 1) {
    $(".validateQuestion").show();
    return false;
  }
});
</script>

app/views/questions/destroy.js.erb
$("." + <%= @question.id%>).hide();

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Back', exam_questions_path(@exam) %>

app/views/questions/edit.js.erb
$("#dialog-form").html("")
$("#dialog-form").modal();
$("#dialog-form").append("<%= escape_javascript(render :partial => 'form')-%>")

app/views/questions/index.html.erb
<table width="100%" id="questions_page_top">
  <tr>
    <td width="100%" id="question_count">
      <% i = 1 %>
      <% @questions.each do |question| %>
        <a href="#<%= question.id %>" id="each_number" title="<%= question.description%>"><%= i %></a>
        <% i += 1 %>
      <% end %>.......
      <b id="add_question">Add Question</b>
      <b><%= link_to 'Save Exam', exams_path(:create_exam => true), :id => "submit_exam" %></b>
    </td>
  </tr>
</table>
<br/><br/>

<div id="accordion">
  <% ques_num = 0 %>
  <% @questions.each do |question| %>
    <% if question.id.present? %>
      <h3 class="<%= question.id%>"><b>Ques <%= ques_num += 1 %> : </b><%= question.description.first(100) %>...</h3>
      <div class="<%= question.id%>">
        <a href="#questions_page_top">Top</a>
        <%= link_to image_tag( 'edit.png', :border=>0, :title=>'Edit', :size => "16x16"), edit_exam_question_path(question.exam, question) %>
        <%= link_to image_tag( 'iconDelete.gif', :border=>0, :title=>'Delete', :size => "16x16"), [question.exam, question], :confirm => 'Are you sure?', :method => :delete, :remote => true %>
        <b>Full Ques : </b>
        <div id="question">
          <%= question.description %><br/>
          <center><%= image_tag question.image_url(:thumb).to_s if question.image_url.present? %></center>
        </div>
        <div id="ques_answers">
          <%= render question.answers %>
          <%= link_to 'Add Answer', new_exam_question_answer_path(question.exam, question) %>
        </div>
      </div>
    <% end %>
    <br><br>
  <% end %>
</div>
<!-- modal window to add new question -->
<%= render 'dialog' %>

<style>
body { font-size: 62.5%; }
.ui-dialog .ui-state-error { padding: .3em; }
.validateQuestion { border: 1px solid transparent; padding: 0.3em; color: red; }
</style>
<script> 
$("#add_question").click(function() {
  $( "#dialog-form" ).dialog("open");
});

$( "#dialog-form" ).dialog({
  autoOpen: false,
  height: 300,
  width: 350,
  modal: true,
  close: function() {
    $( this ).dialog( "close" );
  }
});

$(function() {
  $( "#accordion" ).accordion();
});
</script>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<table width="100%">
  <tr>
    <td width="100%" id="question_count">
      <% i = 1 %><b>Go to Question : </b>
      <% @exam.questions.each do |question| %>
        <%= link_to "#{i}", exam_question_path(@exam, question), :id => "each_number" %>
        <% i += 1 %>
      <% end %>
    </td>
  </tr>
</table>
<br/>

<table width="100%">
  <tr>
  	<td id='ques_button'><b>Ques <%= @current_ques_index + 1 %> : </b></br><%= @question.description %></td>
  </tr> 
  <tr>
  	<td><%= render "answers/answer_form" %></td>
  </tr> 
</table>